version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
     - "5672:5672"
     - "15672:15672"
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    command: /bin/bash ./entrypoint.sh
    ports:
     - "1433:1433"
    environment:
      SA_PASSWORD: "MTsample1"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - ./db/mssql/docker-entrypoint.sh:/entrypoint.sh
      - ./db/mssql/docker-db-init.sh:/db-init.sh
      - ./db/mssql/init.sql:/db-init.sql
  postgres:
    image: "postgres:13.1"
    environment:
      - "POSTGRES_PASSWORD=Password12!"
    ports:
      - 5432:5432